### ISSUE TITLE
CРС

### ISSUE THREAD

**Issue by Redbull1** [iopjklbnm/-#2]
Знайти  фотографію  кота

**Comment by andes216** [comment]
https://www.google.com.ua/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwipotPHtK_QAhULVSwKHZSSC0MQjRwIBw&url=https%3A%2F%2Fuk.wikipedia.org%2Fwiki%2F%25D0%259A%25D1%2596%25D1%2582&psig=AFQjCNGuEyDCt9xNuDjeyuEJi-Wu4i9QHA&ust=1479459042613734
